theme = "catppuccin_mocha"
[keys.normal]
C-g = ":sh kitty @ launch --no-response --cwd=current --type=overlay --copy-env lazygit"
C-y = ":sh kitty @ launch --no-response --cwd=current --type=overlay --copy-env yazi"
