[colors.primary]
background = "#27211e"
foreground = "#d2d4db"

[colors.cursor]
text = "#27211e"
cursor = "#d2d4db"

[colors.selection]
text = "#d2d4db"
background = "#433c39"

[colors.normal]
black   = "#1b1512"
red     = "#fac0e4"
green   = "#d1db9f"
yellow  = "#f6cc9b"
blue    = "#acd6ff"
magenta = "#d8caff"
cyan    = "#93e4ee"
white   = "#d2d4db"

[colors.bright]
black   = "#605855"
red     = "#fac0e4"
green   = "#d1db9f"
yellow  = "#f6cc9b"
blue    = "#acd6ff"
magenta = "#d8caff"
cyan    = "#a6e5c3"
white   = "#eef1f8"

[[colors.indexed_colors]]
index = 16
color = "#ffc1b9"

[[colors.indexed_colors]]
index = 17
color = "#f6cc9b"
